# Generated by Django 5.2.6 on 2025-09-18 09:49

import django.db.models.deletion
import loan.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('meter', '0005_alter_meter_id_alter_metertoken_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('loan_id', models.CharField(default=loan.models.generate_loan_id, max_length=10, unique=True)),
                ('purpose', models.TextField()),
                ('amount_requested', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_approved', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tenure_months', models.IntegerField(default=6)),
                ('interest_rate', models.DecimalField(decimal_places=2, default=10.0, max_digits=5)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('DISBURSED', 'Disbursed'), ('COMPLETED', 'Completed'), ('DEFAULTED', 'Defaulted')], default='PENDING', max_length=20)),
                ('credit_score', models.IntegerField(blank=True, null=True)),
                ('monthly_expenditure', models.CharField(max_length=50)),
                ('purchase_frequency', models.CharField(max_length=20)),
                ('payment_consistency', models.CharField(max_length=20)),
                ('disconnection_history', models.CharField(max_length=30)),
                ('meter_sharing', models.CharField(max_length=20)),
                ('monthly_income', models.CharField(max_length=30)),
                ('income_stability', models.CharField(max_length=30)),
                ('consumption_level', models.CharField(max_length=30)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LoanDisbursement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('disbursement_date', models.DateTimeField(auto_now_add=True)),
                ('disbursed_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('units_disbursed', models.FloatField()),
                ('token', models.CharField(default=loan.models.generate_token, max_length=8, unique=True)),
                ('token_expiry', models.DateTimeField()),
                ('loan_application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='disbursement', to='loan.loanapplication')),
                ('meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_disbursements', to='meter.meter')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LoanRepayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('units_paid', models.FloatField()),
                ('is_on_time', models.BooleanField(default=True)),
                ('payment_reference', models.CharField(max_length=50, unique=True)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repayments', to='loan.loanapplication')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
