# Generated by Django 5.2.6 on 2025-09-18 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='user_notified',
            field=models.BooleanField(default=False),
        ),
    ]
