# Generated by Django 5.2.6 on 2025-09-20 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0002_loanapplication_user_notified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanapplication',
            name='consumption_level',
            field=models.CharField(choices=[('Very low (<50 kWh)', 'Very low (<50 kWh)'), ('Low (50–99 kWh)', 'Low (50–99 kWh)'), ('Moderate (100–200 kWh)', 'Moderate (100–200 kWh)'), ('High (>200 kWh)', 'High (>200 kWh)'), ('Extremely high (>300 kWh)', 'Extremely high (>300 kWh)')], max_length=30),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='disconnection_history',
            field=models.CharField(choices=[('No disconnections', 'No disconnections'), ('1–2 disconnections', '1–2 disconnections'), ('3–4 disconnections', '3–4 disconnections'), ('>4 disconnections', '>4 disconnections'), ('Frequently disconnected', 'Frequently disconnected')], max_length=30),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='income_stability',
            field=models.CharField(choices=[('Fixed and stable', 'Fixed and stable'), ('Regular but variable', 'Regular but variable'), ('Seasonal income', 'Seasonal income'), ('Irregular but frequent', 'Irregular but frequent'), ('Unstable income', 'Unstable income')], max_length=30),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='meter_sharing',
            field=models.CharField(choices=[('No sharing', 'No sharing'), ('Shared with 1 household', 'Shared with 1 household'), ('Shared with 2+ households', 'Shared with 2+ households'), ('Commercial sharing', 'Commercial sharing')], max_length=30),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='monthly_expenditure',
            field=models.CharField(choices=[('<50,000 UGX', '<50,000 UGX'), ('50,000–100,000 UGX', '50,000–100,000 UGX'), ('100,001–200,000 UGX', '100,001–200,000 UGX'), ('200,001–300,000 UGX', '200,001–300,000 UGX'), ('>300,000 UGX', '>300,000 UGX')], max_length=50),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='monthly_income',
            field=models.CharField(choices=[('<100,000 UGX', '<100,000 UGX'), ('100,000–199,999 UGX', '100,000–199,999 UGX'), ('200,000–499,999 UGX', '200,000–499,999 UGX'), ('500,000–999,999 UGX', '500,000–999,999 UGX'), ('>1,000,000 UGX', '>1,000,000 UGX')], max_length=30),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='payment_consistency',
            field=models.CharField(choices=[('Always on time', 'Always on time'), ('Often on time', 'Often on time'), ('Sometimes late', 'Sometimes late'), ('Mostly late', 'Mostly late'), ('Never paid', 'Never paid')], max_length=20),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='purchase_frequency',
            field=models.CharField(choices=[('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Bi-weekly', 'Bi-weekly'), ('Monthly', 'Monthly'), ('Rarely', 'Rarely')], max_length=20),
        ),
    ]
