# Generated by Django 5.2.6 on 2025-09-20 12:57

import loan.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0003_alter_loanapplication_consumption_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loandisbursement',
            name='token',
            field=models.CharField(default=loan.models.generate_token, max_length=10, unique=True),
        ),
    ]
