# Generated by Django 5.2.6 on 2025-10-10 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0004_alter_loandisbursement_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='loan_tier',
            field=models.CharField(blank=True, choices=[('BRONZE', 'Bronze'), ('SILVER', 'Silver'), ('GOLD', 'Gold'), ('PLATINUM', 'Platinum')], max_length=20, null=True),
        ),
    ]
