# Generated by Django 5.2.6 on 2025-10-18 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0005_loanapplication_loan_tier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loanapplication',
            name='consumption_level',
        ),
        migrations.RemoveField(
            model_name='loanapplication',
            name='disconnection_history',
        ),
        migrations.RemoveField(
            model_name='loanapplication',
            name='income_stability',
        ),
        migrations.RemoveField(
            model_name='loanapplication',
            name='meter_sharing',
        ),
        migrations.RemoveField(
            model_name='loanapplication',
            name='monthly_expenditure',
        ),
        migrations.RemoveField(
            model_name='loanapplication',
            name='monthly_income',
        ),
        migrations.RemoveField(
            model_name='loanapplication',
            name='payment_consistency',
        ),
        migrations.RemoveField(
            model_name='loanapplication',
            name='purchase_frequency',
        ),
    ]
