# Generated by Django 5.2.6 on 2025-10-22 10:33

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0006_remove_loanapplication_consumption_level_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectricityTariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tariff_code', models.CharField(max_length=20, unique=True)),
                ('tariff_name', models.CharField(max_length=100)),
                ('tariff_type', models.CharField(choices=[('DOMESTIC', 'Domestic'), ('COMMERCIAL', 'Commercial'), ('INDUSTRIAL', 'Industrial')], default='DOMESTIC', max_length=20)),
                ('voltage_level', models.CharField(max_length=50)),
                ('voltage_value', models.CharField(blank=True, max_length=20)),
                ('service_charge', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('is_active', models.BooleanField(default=True)),
                ('effective_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='tariff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='loan_applications', to='loan.electricitytariff'),
        ),
        migrations.CreateModel(
            name='TariffBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_name', models.CharField(max_length=100)),
                ('min_units', models.IntegerField(default=0)),
                ('max_units', models.IntegerField(blank=True, null=True)),
                ('rate_per_unit', models.DecimalField(decimal_places=2, max_digits=8)),
                ('block_order', models.IntegerField(default=0)),
                ('tariff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='loan.electricitytariff')),
            ],
            options={
                'ordering': ['block_order'],
            },
        ),
    ]
