# Generated by Django 5.2.6 on 2025-10-22 10:34

from django.db import migrations

def add_domestic_tariff_blocks(apps, schema_editor):
    ElectricityTariff = apps.get_model('loan', 'ElectricityTariff')
    TariffBlock = apps.get_model('loan', 'TariffBlock')
    
    domestic_tariff, created = ElectricityTariff.objects.get_or_create(
        tariff_code="CODE10.1",
        defaults={
            'tariff_name': "Domestic Consumers",
            'tariff_type': "DOMESTIC",
            'voltage_level': "Low voltage single phase supply",
            'voltage_value': "240 volts",
            'service_charge': 0,
            'is_active': True
        }
    )
    
    blocks_data = [
        {'block_name': 'First 15 kWh', 'min_units': 1, 'max_units': 15, 'rate_per_unit': 250.0, 'block_order': 1},
        {'block_name': 'Units between 16-80 kWh', 'min_units': 16, 'max_units': 80, 'rate_per_unit': 756.2, 'block_order': 2},
        {'block_name': 'Units between 81-150 kWh', 'min_units': 81, 'max_units': 150, 'rate_per_unit': 412.0, 'block_order': 3},
        {'block_name': 'Units above 150 kWh', 'min_units': 151, 'max_units': None, 'rate_per_unit': 756.2, 'block_order': 4},
    ]
    
    for block_data in blocks_data:
        TariffBlock.objects.get_or_create(
            tariff=domestic_tariff,
            block_name=block_data['block_name'],
            defaults=block_data
        )

def reverse_tariff_blocks(apps, schema_editor):
    ElectricityTariff = apps.get_model('loan', 'ElectricityTariff')
    ElectricityTariff.objects.filter(tariff_code="CODE10.1").delete()

    

class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0007_electricitytariff_loanapplication_tariff_tariffblock'),
    ]

    operations = [
        migrations.RunPython(add_domestic_tariff_blocks, reverse_tariff_blocks),
    ]
