# Generated by Django 5.2.6 on 2025-10-25 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0009_loanrepayment_momo_external_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanapplication',
            name='tariff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='loan.electricitytariff'),
        ),
    ]
