# Generated by Django 6.0 on 2026-02-14 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0010_alter_loanapplication_tariff'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('display_name', models.CharField(max_length=50)),
                ('min_score', models.IntegerField()),
                ('max_score', models.IntegerField()),
                ('max_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['min_score'],
            },
        ),
    ]

    