# Generated by Django 6.0 on 2026-02-14 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0011_loantier'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loanapplication',
            options={},
        ),
        migrations.RemoveField(
            model_name='loanapplication',
            name='loan_tier',
        ),
        migrations.RemoveField(
            model_name='loanapplication',
            name='rejection_reason',
        ),
        migrations.RemoveField(
            model_name='loanapplication',
            name='tariff',
        ),
        migrations.RemoveField(
            model_name='loanapplication',
            name='user_notified',
        ),
    ]
