# Generated by Django 6.0 on 2026-02-14 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0012_alter_loanapplication_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loanapplication',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='loan_tier',
            field=models.CharField(blank=True, choices=[('BRONZE', 'Bronze'), ('SILVER', 'Silver'), ('GOLD', 'Gold'), ('PLATINUM', 'Platinum')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='tariff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='loan.electricitytariff'),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='user_notified',
            field=models.BooleanField(default=False),
        ),
    ]
