# Generated by Django 5.2 on 2026-06-12 05:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0014_usercreditsignal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditScoreFactors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('on_time_payments', models.IntegerField(default=0)),
                ('late_payments', models.IntegerField(default=0)),
                ('total_repayments', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('repayment_consistency_score', models.FloatField(default=0)),
                ('total_units_purchased', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('purchase_frequency', models.IntegerField(default=0)),
                ('wallet_usage_count', models.IntegerField(default=0)),
                ('wallet_transaction_volume', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('units_shared', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('units_received', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('sharing_count', models.IntegerField(default=0)),
                ('loans_taken', models.IntegerField(default=0)),
                ('loans_completed', models.IntegerField(default=0)),
                ('loans_defaulted', models.IntegerField(default=0)),
                ('total_loan_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('account_age_days', models.IntegerField(default=0)),
                ('last_activity_date', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credit_factors', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CreditScoreHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_score', models.IntegerField()),
                ('new_score', models.IntegerField()),
                ('change_amount', models.IntegerField()),
                ('reason', models.CharField(max_length=200)),
                ('event_type', models.CharField(choices=[('LOAN_APPLICATION', 'Loan Application'), ('LOAN_REPAYMENT', 'Loan Repayment'), ('UNIT_PURCHASE', 'Unit Purchase'), ('WALLET_USAGE', 'Wallet Usage'), ('LATE_PAYMENT', 'Late Payment'), ('ON_TIME_PAYMENT', 'On-Time Payment'), ('SHARE_UNITS', 'Share Units'), ('METER_REGISTRATION', 'Meter Registration')], max_length=50)),
                ('reference_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_score_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
