# Generated by Django 5.2 on 2026-06-15 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0015_tariff_date_range_lifeline_block'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tariffblock',
            name='is_lifeline_block',
            field=models.BooleanField(default=False, help_text='If true, this block only applies to lifeline-eligible customers'),
        ),
        migrations.AlterField(
            model_name='tariffblock',
            name='non_lifeline_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Rate charged for ineligible customers in a lifeline block', max_digits=8, null=True),
        ),
    ]
