# Generated by Django 5.2 on 2026-07-07 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0015_creditscorefactors_creditscorehistory'),
        ('loan', '0017_loanrepayment_paid_by_is_anonymous'),
    ]

    operations = [
    ]
