# Generated by Django 5.2 on 2026-07-14 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0018_merge_20260707_0328'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditscorefactors',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
