# Generated by Django 5.2 on 2026-09-30 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0019_creditscorefactors_created_at'),
        ('meter', '0022_alter_meternotification_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='intended_meter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='intended_loans', to='meter.meter'),
        ),
    ]
