# Generated by Django 3.1.2 on 2025-01-19 11:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('modify_date', models.DateTimeField(auto_now=True, verbose_name='date modified')),
                ('wallet_id', models.CharField(max_length=10, unique=True)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WalletLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('modify_date', models.DateTimeField(auto_now=True, verbose_name='date modified')),
                ('current_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=20, null=True)),
                ('incoming_amount', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=20, null=True)),
                ('outgoing_amount', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=20, null=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.wallet')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
