# Generated by Django 3.1.2 on 2025-01-19 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_wallet_walletlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_role',
            field=models.CharField(choices=[('ADMIN', 'admin'), ('CLIENT', 'client')], default='CLIENT', max_length=8),
        ),
    ]
