# Generated by Django 3.1.2 on 2025-02-01 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20250119_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_purchase_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='monthly_unit_balance',
            field=models.FloatField(default=0),
        ),
    ]
