# Generated by Django 5.2.6 on 2025-10-13 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_consolidated_migration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='wallet_id',
            field=models.CharField(editable=False, max_length=10, unique=True),
        ),
    ]
