# Generated by Django 5.2 on 2026-06-15 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_profile_lifeline_eligible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='lifeline_eligible',
            field=models.BooleanField(default=True),
        ),
    ]
