# Generated by Django 5.2 on 2026-06-25 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_user_ussd_pin_hash'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='ussd_pin_hash',
        ),
    ]
