# Generated by Django 5.2 on 2026-04-06 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ussd', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='ussdsession',
            new_name='ussd_ussdse_phone_n_1664d4_idx',
            old_name='ussd_ussdse_phone_n_2425f8_idx',
        ),
        migrations.RenameIndex(
            model_name='ussdsession',
            new_name='ussd_ussdse_expires_748893_idx',
            old_name='ussd_ussdse_expires_0aa5ff_idx',
        ),
        migrations.AlterField(
            model_name='ussdsession',
            name='expires_at',
            field=models.DateTimeField(),
        ),
    ]
