# Generated by Django 6.0 on 2026-01-22 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meter', '0010_alter_meter_units_alter_metertoken_units'),
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meterbalance',
            name='meter',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='balance_record', to='meter.meter'),
        ),
    ]
