# Generated by Django 5.2 on 2026-06-12 02:25

import django.core.validators
import django.db.models.deletion
import wallet.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_meterbalance_meter'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='unit_balance', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Unit Balance',
                'verbose_name_plural': 'Unit Balances',
            },
        ),
        migrations.CreateModel(
            name='UnitTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('transaction_type', models.CharField(choices=[('CREDIT', 'Credit'), ('DEBIT', 'Debit'), ('SHARE_OUT', 'Share Out'), ('SHARE_IN', 'Share In'), ('PURCHASE', 'Purchase'), ('LOAN_DISBURSEMENT', 'Loan Disbursement'), ('LOAN_REPAYMENT', 'Loan Repayment')], max_length=20)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('reference', models.CharField(default=wallet.models.generate_transaction_ref, max_length=100, unique=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('unit_balance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='wallet.unitbalance')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['reference'], name='wallet_unit_referen_c49204_idx'), models.Index(fields=['unit_balance', 'created_at'], name='wallet_unit_unit_ba_7abe4f_idx')],
            },
        ),
    ]
