# Generated by Django 3.1.2 on 2025-01-19 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meter', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UnitTransaction',
        ),
    ]
