# Generated by Django 3.1.2 on 2025-01-19 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meter', '0002_delete_unittransaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meter',
            name='last_reported',
        ),
    ]
