# Generated by Django 5.2.6 on 2025-09-08 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meter', '0004_metertoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meter',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='metertoken',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
