# Generated by Django 5.2.6 on 2025-09-20 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0003_alter_loanapplication_consumption_level_and_more'),
        ('meter', '0005_alter_meter_id_alter_metertoken_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='metertoken',
            name='loan_application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='loan.loanapplication'),
        ),
        migrations.AddField(
            model_name='metertoken',
            name='source',
            field=models.CharField(choices=[('PURCHASE', 'Purchase'), ('LOAN', 'Loan'), ('TRANSFER', 'Transfer')], default='PURCHASE', max_length=10),
        ),
    ]
