# Generated by Django 5.2.6 on 2025-09-20 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0004_alter_loandisbursement_token'),
        ('meter', '0006_metertoken_loan_application_metertoken_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metertoken',
            name='loan_application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tokens', to='loan.loanapplication'),
        ),
    ]
