# Generated by Django 5.2.6 on 2025-09-20 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meter', '0007_alter_metertoken_loan_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='metertoken',
            name='meter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='meter.meter'),
        ),
    ]
