# Generated by Django 5.2.6 on 2025-11-23 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meter', '0008_metertoken_meter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metertoken',
            name='meter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='meter.meter'),
        ),
    ]
