# Generated by Django 6.0 on 2026-03-26 10:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meter', '0010_alter_meter_units_alter_metertoken_units'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='metertoken',
            name='is_reverted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='metertoken',
            name='reverted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='metertoken',
            name='share_sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='share_tokens_sent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='metertoken',
            name='share_transaction_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='metertoken',
            name='token_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='metertoken',
            name='source',
            field=models.CharField(choices=[('PURCHASE', 'Purchase'), ('LOAN', 'Loan'), ('SHARE', 'Share'), ('TRANSFER', 'Transfer')], default='PURCHASE', max_length=10),
        ),
    ]
