# Generated by Django 6.0 on 2026-03-26 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meter', '0011_metertoken_is_reverted_metertoken_reverted_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metertoken',
            name='is_reverted',
        ),
        migrations.RemoveField(
            model_name='metertoken',
            name='reverted_at',
        ),
        migrations.RemoveField(
            model_name='metertoken',
            name='token_expiry',
        ),
    ]
