# Generated by Django 5.2 on 2026-06-16 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meter', '0012_remove_metertoken_is_reverted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meter',
            name='iot_device_token',
            field=models.CharField(blank=True, help_text='ThingsBoard device access token used to push purchased units.', max_length=128, null=True),
        ),
    ]
