# Generated by Django 5.2 on 2026-06-06 15:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0014_usercreditsignal'),
        ('meter', '0012_remove_metertoken_is_reverted_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='meter',
            name='deactivated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meter',
            name='deactivated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deactivated_meters', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='meter',
            name='deactivation_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meter',
            name='deactivation_reason',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='meter',
            name='label',
            field=models.CharField(blank=True, default='Home', max_length=50),
        ),
        migrations.AddField(
            model_name='meter',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('SUSPENDED', 'Suspended')], default='ACTIVE', max_length=12),
        ),
        migrations.AlterField(
            model_name='meter',
            name='static_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('modify_date', models.DateTimeField(auto_now=True, verbose_name='date modified')),
                ('transaction_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('transaction_type', models.CharField(choices=[('PURCHASE', 'Purchase'), ('GENERATE_TOKEN', 'Generate Token'), ('TRANSFER_OUT', 'Transfer Out'), ('TRANSFER_IN', 'Transfer In'), ('CREDIT', 'Credit'), ('REPAYMENT_AUTO', 'Repayment (Auto)'), ('REPAYMENT_DIRECT', 'Repayment (Direct)'), ('PENALTY', 'Penalty'), ('REFUND', 'Refund')], db_index=True, max_length=20)),
                ('amount_kwh', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('amount_ugx', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('source', models.CharField(blank=True, default='', max_length=100)),
                ('destination', models.CharField(blank=True, default='', max_length=100)),
                ('sts_token', models.CharField(blank=True, default='', max_length=30)),
                ('payment_reference', models.CharField(blank=True, default='', max_length=100)),
                ('status', models.CharField(choices=[('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('PENDING', 'Pending'), ('REVERSED', 'Reversed')], db_index=True, default='PENDING', max_length=12)),
                ('channel', models.CharField(choices=[('USSD', 'USSD'), ('MOBILE_APP', 'Mobile App'), ('WEB_PORTAL', 'Web Portal'), ('ADMIN', 'Admin')], default='USSD', max_length=12)),
                ('failure_reason', models.CharField(blank=True, default='', max_length=200)),
                ('is_flagged', models.BooleanField(default=False)),
                ('flag_reason', models.CharField(blank=True, default='', max_length=200)),
                ('refund_reason', models.TextField(blank=True, default='')),
                ('refunded_at', models.DateTimeField(blank=True, null=True)),
                ('loan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='loan.loanapplication')),
                ('meter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='meter.meter')),
                ('refunded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refunds_issued', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-create_date'],
                'indexes': [models.Index(fields=['user', 'create_date'], name='meter_trans_user_id_73f703_idx'), models.Index(fields=['transaction_type', 'status'], name='meter_trans_transac_880dc1_idx'), models.Index(fields=['meter', 'create_date'], name='meter_trans_meter_i_819e7c_idx'), models.Index(fields=['is_flagged'], name='meter_trans_is_flag_5c9f44_idx')],
            },
        ),
    ]
