# Generated by Django 5.2 on 2026-06-16 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meter', '0013_meter_iot_device_token'),
        ('meter', '0014_meter_architecture_pending_units'),
    ]

    operations = [
    ]
