# Generated by Django 5.2 on 2026-06-22 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meter', '0017_meter_power_usage'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='meterbalancesnapshot',
            new_name='meter_meter_meter_i_7236ad_idx',
            old_name='meter_meter_meter_i_8a1f2c_idx',
        ),
        migrations.RenameIndex(
            model_name='meternotification',
            new_name='meter_meter_user_id_4741ae_idx',
            old_name='meter_meter_user_id_6f0a2a_idx',
        ),
        migrations.RenameIndex(
            model_name='meternotification',
            new_name='meter_meter_device__4fee65_idx',
            old_name='meter_meter_device__a1b2c3_idx',
        ),
        migrations.RenameIndex(
            model_name='meterusagedaily',
            new_name='meter_meter_meter_i_808a9f_idx',
            old_name='meter_meter_meter_i_9b2e3d_idx',
        ),
        migrations.AlterField(
            model_name='meterbalancesnapshot',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='meterbalancesnapshot',
            name='modify_date',
            field=models.DateTimeField(auto_now=True, verbose_name='date modified'),
        ),
        migrations.AlterField(
            model_name='meternotification',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='meternotification',
            name='modify_date',
            field=models.DateTimeField(auto_now=True, verbose_name='date modified'),
        ),
        migrations.AlterField(
            model_name='meternotification',
            name='units_kwh',
            field=models.DecimalField(decimal_places=4, max_digits=12),
        ),
        migrations.AlterField(
            model_name='meterusagedaily',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='meterusagedaily',
            name='kwh_used',
            field=models.DecimalField(decimal_places=4, max_digits=12),
        ),
        migrations.AlterField(
            model_name='meterusagedaily',
            name='modify_date',
            field=models.DateTimeField(auto_now=True, verbose_name='date modified'),
        ),
    ]
