# Generated by Django 5.2 on 2026-06-24 05:19

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meter', '0019_meter_soft_delete'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='deletedmeterrecord',
            new_name='meter_delet_origina_ea578b_idx',
            old_name='meter_del_no_dt_idx',
        ),
        migrations.RenameIndex(
            model_name='deletedmeterrecord',
            new_name='meter_delet_former__576494_idx',
            old_name='meter_del_user_dt_idx',
        ),
        migrations.AlterField(
            model_name='deletedmeterrecord',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='deletedmeterrecord',
            name='modify_date',
            field=models.DateTimeField(auto_now=True, verbose_name='date modified'),
        ),
        migrations.AlterField(
            model_name='meter',
            name='pending_units',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='STS: units waiting for token generation. AMI: units queued for ThingsBoard delivery when the meter is offline.', max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
