# Generated by Django 5.2 on 2026-06-25 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meter', '0020_rename_meter_del_no_dt_idx_meter_delet_origina_ea578b_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meternotification',
            name='notification_type',
            field=models.CharField(choices=[('LOW_UNITS', 'Low units'), ('LOAN_APPLICATION', 'Loan application'), ('LOAN_DISBURSEMENT', 'Loan disbursement')], default='LOW_UNITS', max_length=32),
        ),
    ]
