# Generated by Django 5.2 on 2026-07-14 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meter', '0021_alter_meternotification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meternotification',
            name='notification_type',
            field=models.CharField(choices=[('LOW_UNITS', 'Low units'), ('LOAN_APPLICATION', 'Loan application'), ('LOAN_DISBURSEMENT', 'Loan disbursement'), ('LOAN_REPAYMENT', 'Loan repayment')], default='LOW_UNITS', max_length=32),
        ),
    ]
