# Generated by Django 5.2 on 2026-09-30 09:34

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0020_loanapplication_intended_meter'),
        ('meter', '0022_alter_meternotification_notification_type'),
        ('transactions', '0007_paymentintent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EnergyAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_kwh', models.DecimalField(decimal_places=2, max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('loan_disbursement', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='energy_allocation', to='loan.loandisbursement')),
                ('meter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='energy_allocations', to='meter.meter')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='energy_allocations', to=settings.AUTH_USER_MODEL)),
                ('purchase_intent', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='energy_allocation', to='transactions.paymentintent')),
            ],
        ),
        migrations.CreateModel(
            name='MeterDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('amount_kwh', models.DecimalField(decimal_places=2, max_digits=20)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('DISPATCHED', 'Dispatched'), ('APPLIED', 'Applied'), ('FAILED', 'Failed'), ('EXPIRED', 'Expired'), ('OUTCOME_UNKNOWN', 'Outcome Unknown')], db_index=True, default='QUEUED', max_length=20)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dispatched_at', models.DateTimeField(blank=True, null=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.CharField(blank=True, max_length=120)),
                ('allocation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to='meter.energyallocation')),
            ],
        ),
        migrations.CreateModel(
            name='SimulatedMeter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('credential_hash', models.CharField(max_length=128)),
                ('applied_kwh', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20)),
                ('consumed_wh', models.BigIntegerField(default=0)),
                ('boot_id', models.UUIDField(blank=True, null=True)),
                ('last_sequence', models.BigIntegerField(blank=True, null=True)),
                ('last_counter_wh', models.BigIntegerField(blank=True, null=True)),
                ('last_contact_at', models.DateTimeField(blank=True, null=True)),
                ('reported_relay_state', models.CharField(default='UNKNOWN', max_length=10)),
                ('requested_relay_state', models.CharField(default='UNKNOWN', max_length=10)),
                ('reset_count', models.PositiveIntegerField(default=0)),
                ('meter', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='simulator', to='meter.meter')),
            ],
        ),
        migrations.CreateModel(
            name='SimulatedCommand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command_id', models.UUIDField(unique=True)),
                ('amount_kwh', models.DecimalField(decimal_places=2, max_digits=20)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('delivery', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='simulated_command', to='meter.meterdelivery')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commands', to='meter.simulatedmeter')),
            ],
        ),
        migrations.CreateModel(
            name='SimulatedTelemetry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.UUIDField()),
                ('boot_id', models.UUIDField()),
                ('sequence', models.BigIntegerField()),
                ('cumulative_wh', models.BigIntegerField()),
                ('measured_at', models.DateTimeField()),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('reported_relay_state', models.CharField(max_length=10)),
                ('classification', models.CharField(max_length=24)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='telemetry', to='meter.simulatedmeter')),
            ],
        ),
        migrations.AddConstraint(
            model_name='energyallocation',
            constraint=models.CheckConstraint(condition=models.Q(('amount_kwh__gt', 0)), name='allocation_positive_kwh'),
        ),
        migrations.AddConstraint(
            model_name='energyallocation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('loan_disbursement__isnull', True), ('purchase_intent__isnull', False)), models.Q(('loan_disbursement__isnull', False), ('purchase_intent__isnull', True)), _connector='OR'), name='allocation_one_source'),
        ),
        migrations.AddConstraint(
            model_name='meterdelivery',
            constraint=models.CheckConstraint(condition=models.Q(('amount_kwh__gt', 0)), name='delivery_positive_kwh'),
        ),
        migrations.AddConstraint(
            model_name='simulatedtelemetry',
            constraint=models.UniqueConstraint(fields=('device', 'event_id'), name='sim_telemetry_event_unique'),
        ),
    ]
