# Generated by Django 5.2 on 2026-09-30 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meter', '0023_energyallocation_meterdelivery_simulatedmeter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulatedmeter',
            name='last_measured_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
