"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
import os
from pathlib import Path
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# =============================
# Helper function for env variables
# =============================
def get_env_variable(var_name, default=None, cast=str):
    """
    Get an environment variable or return default.
    Supports casting (str, int, bool, etc.)
    """
    value = os.getenv(var_name, default)
    if value is None:
        raise Exception(f"Missing required environment variable: {var_name}")
    try:
        return cast(value)
    except Exception as e:
        raise ValueError(f"Error casting environment variable {var_name}: {e}")



REDIS_HOST = get_env_variable("REDIS_HOST", "127.0.0.1")
REDIS_PORT = get_env_variable("REDIS_PORT", 6379, cast=int)
REDIS_URL = get_env_variable("REDIS_URL", f"redis://{REDIS_HOST}:{REDIS_PORT}/0")
BASE_URL = get_env_variable("BASE_URL", "http://localhost:8000/api/v1")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/
load_dotenv(BASE_DIR / ".env")

from backend.feature_config import load_feature_flags, parse_feature_bool
FEATURE_FLAGS = load_feature_flags(os.environ)
SIMULATED_METER_ENABLED = parse_feature_bool(
    os.environ.get("SIMULATED_METER_ENABLED", "false"), name="SIMULATED_METER_ENABLED",
)
# SECURITY WARNING: keep the secret key used in production secret!
DEBUG = get_env_variable("DEBUG", "True") == "True"
SECRET_KEY = get_env_variable("SECRET_KEY", "development-only-unsafe-key" if DEBUG else None)

# =============================
# Frontend URL (used in verification/reset email links)
# Set FRONTEND_URL=https://energy-share.sun.ac.ug in production .env
# =============================
FRONTEND_URL = get_env_variable("FRONTEND_URL", "http://localhost:3000")

# =============================
# ALLOWED_HOSTS — read from env (comma-separated) or use dev defaults
# =============================
_extra_hosts = [h.strip() for h in get_env_variable("EXTRA_ALLOWED_HOSTS", "").split(',') if h.strip()]
ALLOWED_HOSTS = ['0.0.0.0', 'nginx', 'localhost', '127.0.0.1'] + _extra_hosts

AUTH_USER_MODEL = 'accounts.User'

# =============================
# CORS / CSRF — always allow localhost in dev; add production domain from env
# =============================
_prod_origin = get_env_variable("PRODUCTION_ORIGIN", "")  # e.g. https://energy-share.sun.ac.ug

_base_origins = ['http://localhost:3000', 'http://localhost:3030']
if _prod_origin:
    _base_origins.append(_prod_origin)

CSRF_TRUSTED_ORIGINS = _base_origins
CORS_ALLOWED_ORIGINS = _base_origins
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_ALL_ORIGINS = DEBUG

# =============================
from mtn_momo.config import MTN_MOMO_CONFIG, should_simulate_payments  # noqa: E402

MTN_USE_SIMULATED_PAYMENTS = should_simulate_payments()

THINGSBOARD_BASE_URL = get_env_variable("THINGSBOARD_BASE_URL", "https://iot.energy-share.sun.ac.ug")
# Server-to-server URL when TB runs on the same production host (bypasses public DNS/firewall hairpin).
_THINGSBOARD_INTERNAL_BASE_URL = get_env_variable("THINGSBOARD_INTERNAL_BASE_URL", "")
THINGSBOARD_INTERNAL_BASE_URL = "" if DEBUG else _THINGSBOARD_INTERNAL_BASE_URL
THINGSBOARD_TIMEOUT_SECONDS = get_env_variable("THINGSBOARD_TIMEOUT_SECONDS", 15, cast=int)
THINGSBOARD_VERIFY_SSL = str(
    get_env_variable("THINGSBOARD_VERIFY_SSL", "true")
).strip().lower() in ("1", "true", "yes", "on")
THINGSBOARD_WEBHOOK_SECRET = get_env_variable("THINGSBOARD_WEBHOOK_SECRET", "")
THINGSBOARD_TENANT_USERNAME = get_env_variable("THINGSBOARD_TENANT_USERNAME", "")
THINGSBOARD_TENANT_PASSWORD = get_env_variable("THINGSBOARD_TENANT_PASSWORD", "")
THINGSBOARD_USAGE_TELEMETRY_KEY = get_env_variable("THINGSBOARD_USAGE_TELEMETRY_KEY", "daily_kwh")
AMI_LOW_UNITS_THRESHOLD_KWH = get_env_variable("AMI_LOW_UNITS_THRESHOLD_KWH", 5, cast=float)
AMI_LOW_UNITS_POLL_SECONDS = get_env_variable("AMI_LOW_UNITS_POLL_SECONDS", 1, cast=int)
AMI_LOW_UNITS_ALERT_COOLDOWN_HOURS = get_env_variable("AMI_LOW_UNITS_ALERT_COOLDOWN_HOURS", 6, cast=int)

# USSD: inactivity timeout between user inputs (seconds). Industry default is 90s.
USSD_SESSION_TIMEOUT_SECONDS = get_env_variable("USSD_SESSION_TIMEOUT_SECONDS", 90, cast=int)

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'admin.apps.AdminConfig',
    'accounts',
    'loan',
    'transactions',
    'meter',
    'rest_framework',
    'cities_light',
    'drf_yasg',
    'corsheaders',
    'share',
    'transfer',
    'wallet',
    'ussd',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'accounts.middleware.StaffInactivityMiddleware',
    'admin.middleware.SystemErrorLoggingMiddleware',
]

# Staff admin session: 30 minutes of inactivity expires access (spec Section 1.3)
STAFF_SESSION_INACTIVITY_MINUTES = 30
# 2FA settings
TOTP_ISSUER_NAME = 'gPawa Admin'

# =============================
# AMI Gateway
# MockAMIGateway = pilot simulation; ThingsBoardAMIGateway = real networked meters
# =============================
AMI_GATEWAY = get_env_variable("AMI_GATEWAY", "utils.ami_gateway.MockAMIGateway")
# CRB integration (no-op for pilot; swap to a real provider class when integrating)
CRB_PROVIDER = get_env_variable("CRB_PROVIDER", "loan.crb.NoOpCreditBureauProvider")

# =============================
# Lending compliance (Uganda Tier 4 MFI / Money Lenders Act)
# Statutory cap: 2.8% per month (33.6% per annum).
# These are the legal maximums — configuring ABOVE these values requires
# an explicit regulatory change; the application enforces them as hard ceilings.
# =============================
from decimal import Decimal as _D
MAX_MONTHLY_INTEREST_RATE_PCT = _D(get_env_variable("MAX_MONTHLY_INTEREST_RATE_PCT", "2.8"))
MAX_ANNUAL_INTEREST_RATE_PCT = MAX_MONTHLY_INTEREST_RATE_PCT * 12   # 33.6
# No cumulative interest+penalty+fees may exceed 100% of the principal.
MAX_CUMULATIVE_CHARGES_MULTIPLIER = _D(get_env_variable("MAX_CUMULATIVE_CHARGES_MULTIPLIER", "1.0"))
TOTP_CHALLENGE_MAX_AGE_SECONDS = 300

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'

# =============================
# Base URL
# =============================
# Used by get_base_url() to construct links in emails
DEFAULT_HTTP_PROTOCOL = get_env_variable("DEFAULT_HTTP_PROTOCOL", "http")
DOMAIN_NAME = get_env_variable("DOMAIN_NAME", "localhost:3000")
BASE_URL = get_env_variable("BASE_URL", "http://localhost:8000/api/v1")


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': get_env_variable('DB_NAME', 'energy_share'),
        'USER': get_env_variable('DB_USER', 'energy_user'),
        'PASSWORD': get_env_variable('DB_PASSWORD', ''),
        'HOST': get_env_variable('DB_HOST', 'localhost'),
        'PORT': get_env_variable('DB_PORT', 5432, cast=int),
        "ATOMIC_REQUESTS": True,
        "CONN_MAX_AGE": 60,  
        'OPTIONS': {
            'options': '-c search_path=custom,public',
            'connect_timeout': 10,
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {'min_length': 12},
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Rate limiting settings
SHARE_RATE_LIMIT = 10  # Max shares per hour per user
IP_SHARE_RATE_LIMIT = 50  # Max shares per hour per IP

# Security settings
MINIMUM_SHARE_UNITS = 2
MAXIMUM_SHARE_UNITS = 1000


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
MEDIA_URL = "/media/"
STATIC_ROOT = BASE_DIR / "staticfiles"
MEDIA_ROOT = BASE_DIR / "mediafiles"

# =============================
# Email
# =============================
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = get_env_variable("EMAIL_HOST", "smtp.gmail.com")
EMAIL_PORT = get_env_variable("EMAIL_PORT", 587, cast=int)
EMAIL_USE_TLS = get_env_variable("EMAIL_USE_TLS", "True") == "True"
EMAIL_USE_SSL = get_env_variable("EMAIL_USE_SSL", "False") == "True"
EMAIL_HOST_USER = get_env_variable("EMAIL_HOST_USER", "gpawateam@gmail.com")
EMAIL_HOST_PASSWORD = get_env_variable("EMAIL_HOST_PASSWORD", "")
DEFAULT_FROM_EMAIL = get_env_variable("DEFAULT_EMAIL_SENDER", "gpawateam@gmail.com")
DEFAULT_EMAIL_SENDER = DEFAULT_FROM_EMAIL

# =============================
# Celery & Redis
# =============================
CELERY_BROKER_URL = 'redis://127.0.0.1:6379/0'
CELERY_RESULT_BACKEND = 'redis://127.0.0.1:6379/0'

CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'Africa/Nairobi'

CELERY_BROKER_URL = get_env_variable("CELERY_BROKER_URL", "redis://127.0.0.1:6379/0")
CELERY_RESULT_BACKEND = get_env_variable("CELERY_RESULT_BACKEND", "redis://127.0.0.1:6379/0")
CELERY_TIMEZONE = get_env_variable("CELERY_TIMEZONE", "Africa/Nairobi")
# Run tasks eagerly in local dev to avoid needing Redis/Celery worker
CELERY_TASK_ALWAYS_EAGER = get_env_variable("CELERY_TASK_ALWAYS_EAGER", "True") == "True"
CELERY_TASK_EAGER_PROPAGATES = True
# In dev (ALWAYS_EAGER), don't store results — avoids any backend connection
CELERY_TASK_IGNORE_RESULT = True

from datetime import timedelta

from celery.schedules import crontab

CELERY_BEAT_SCHEDULE = {
    "verified-payment-reconciliation": {
        "task": "transactions.tasks.reconcile_pending_payments",
        "schedule": crontab(minute="*/5"),
        "options": {"queue": "celery"},
    },
    "ami-meter-balance-snapshots": {
        "task": "meter.tasks.snapshot_ami_meter_balances",
        "schedule": crontab(minute=0, hour="*/6"),
        "options": {"queue": "celery"},
    },
    "ami-daily-usage-aggregate": {
        "task": "meter.tasks.aggregate_daily_ami_usage",
        "schedule": crontab(minute=15, hour=1),
        "options": {"queue": "celery"},
    },
    "simulated-meter-outbox": {
        "task": "meter.tasks.dispatch_simulated_outbox",
        "schedule": crontab(minute="*/1"),
        "options": {"queue": "celery"},
    },
    "ami-low-units-poll": {
        "task": "meter.tasks.poll_ami_low_units",
        "schedule": timedelta(seconds=AMI_LOW_UNITS_POLL_SECONDS),
        "options": {"queue": "celery"},
    },
}

# JWT settings
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
}
from datetime import timedelta
SIMPLE_JWT = {
    'AUTH_HEADER_TYPES': ('Bearer',),
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'AUTH_COOKIE': 'AUTHENTICATION_COOKIE', 
    'AUTH_COOKIE_HTTP_ONLY': True,
    'AUTH_COOKIE_SECURE': False, 
    'AUTH_COOKIE_SAMESITE': 'Lax',
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=30),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
}

# Extended refresh when user checks "Remember me" on login (days)
REMEMBER_ME_REFRESH_DAYS = 30
