# Generated by Django 6.0 on 2025-12-27 00:35

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0009_user_consumption_level_user_disconnection_history_and_more'),
        ('meter', '0009_alter_metertoken_meter'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('modify_date', models.DateTimeField(auto_now=True, verbose_name='date modified')),
                ('request_id', models.CharField(max_length=20, unique=True)),
                ('units_to_transfer', models.DecimalField(decimal_places=2, max_digits=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_transfers', to=settings.AUTH_USER_MODEL)),
                ('new_meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='new_transfers', to='meter.meter')),
                ('old_meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='old_transfers', to='meter.meter')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Share',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('modify_date', models.DateTimeField(auto_now=True, verbose_name='date modified')),
                ('share_transaction_id', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('units', models.DecimalField(decimal_places=2, default=0.0, max_digits=20, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('message', models.TextField(blank=True, null=True)),
                ('share_transaction_reference', models.TextField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('verification_code', models.CharField(blank=True, max_length=6, null=True)),
                ('meter_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_records', to='meter.meter')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_transactions', to='accounts.wallet')),
            ],
            options={
                'ordering': ['-create_date'],
                'indexes': [models.Index(fields=['share_transaction_id'], name='share_share_share_t_05d728_idx'), models.Index(fields=['wallet', 'status'], name='share_share_wallet__46435c_idx')],
            },
        ),
        migrations.CreateModel(
            name='ShareTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('modify_date', models.DateTimeField(auto_now=True, verbose_name='date modified')),
                ('share_transaction_id', models.CharField(max_length=20, unique=True)),
                ('units', models.DecimalField(decimal_places=2, max_digits=20, validators=[django.core.validators.MinValueValidator(2.0)])),
                ('direction', models.CharField(choices=[('IN', 'In'), ('OUT', 'Out')], default='IN', max_length=3)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('message', models.TextField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('meter_receive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_transactions', to='meter.meter')),
                ('meter_send', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_transactions', to='meter.meter')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_received_transactions', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_sent_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-create_date'],
                'indexes': [models.Index(fields=['share_transaction_id'], name='share_share_share_t_76e926_idx'), models.Index(fields=['sender', 'receiver'], name='share_share_sender__1d8bf3_idx'), models.Index(fields=['status', 'create_date'], name='share_share_status_44020f_idx')],
            },
        ),
    ]
