# Generated by Django 6.0 on 2026-01-22 12:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('purpose', models.CharField(choices=[('share_units', 'Share Units'), ('transfer_units', 'Transfer Units'), ('login', 'Login'), ('reset_password', 'Reset Password')], max_length=50)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'purpose', 'is_used'], name='share_verif_user_id_bb5bb3_idx'), models.Index(fields=['expires_at'], name='share_verif_expires_08d210_idx'), models.Index(fields=['code', 'purpose'], name='share_verif_code_e7be7c_idx')],
            },
        ),
    ]
