# Generated by Django 5.2 on 2026-06-06 15:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminNotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_notifications', models.BooleanField(default=True)),
                ('sms_notifications', models.BooleanField(default=False)),
                ('loan_approvals', models.BooleanField(default=True)),
                ('user_registrations', models.BooleanField(default=True)),
                ('system_alerts', models.BooleanField(default=True)),
                ('weekly_reports', models.BooleanField(default=False)),
                ('report_schedule', models.CharField(choices=[('weekly', 'Weekly'), ('daily', 'Daily'), ('monthly', 'Monthly'), ('never', 'Never')], default='weekly', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Admin Notification Settings',
                'verbose_name_plural': 'Admin Notification Settings',
            },
        ),
        migrations.CreateModel(
            name='FlaggedAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag_type', models.CharField(choices=[('Volume Spike', 'Volume Spike'), ('Rapid Transfers', 'Rapid Transfers'), ('New Meter Transfer', 'New Meter Transfer'), ('High Credit Usage', 'High Credit Usage'), ('Geographic Anomaly', 'Geographic Anomaly'), ('Manual Flag', 'Manual Flag')], max_length=30)),
                ('trigger_description', models.TextField()),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLEARED', 'Cleared'), ('ESCALATED', 'Escalated')], default='OPEN', max_length=15)),
                ('review_note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_flags', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fraud_flags', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScheduledReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('daily_transaction_summary', 'Daily Transaction Summary'), ('user_adoption', 'User Adoption Report'), ('credit_loan', 'Credit & Loan Report'), ('transfer_activity', 'Transfer Activity Report'), ('revenue_summary', 'Revenue Summary'), ('meter_registration', 'Meter Registration Report'), ('fraud_flags', 'Fraud & Flags Report'), ('system_performance', 'System Performance Report'), ('social_impact', 'Social Impact Report')], max_length=50)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=10)),
                ('recipients', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StaffInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('full_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(blank=True, default='', max_length=20)),
                ('department', models.CharField(blank=True, default='', max_length=100)),
                ('role', models.CharField(max_length=20)),
                ('token', models.CharField(max_length=64, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('EXPIRED', 'Expired')], default='PENDING', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('invited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_invitations_sent', to=settings.AUTH_USER_MODEL)),
                ('staff_user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_invitation', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdminActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('details', models.JSONField(default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='portal_admi_user_id_b6bc58_idx')],
            },
        ),
        migrations.CreateModel(
            name='AdminSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('login_time', models.DateTimeField(auto_now_add=True)),
                ('logout_time', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-login_time'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='portal_admi_user_id_b1fbdf_idx'), models.Index(fields=['expires_at'], name='portal_admi_expires_0a2f12_idx')],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('action_type', models.CharField(choices=[('User Edit', 'User Edit'), ('Account Suspension', 'Account Suspension'), ('Account Reactivation', 'Account Reactivation'), ('Credential Reset', 'Credential Reset'), ('KYC Verify', 'KYC Verify'), ('KYC Reject', 'KYC Reject'), ('Meter Register', 'Meter Register'), ('Meter Deactivate', 'Meter Deactivate'), ('Meter Transfer', 'Meter Transfer'), ('Refund', 'Refund'), ('Penalty Waiver', 'Penalty Waiver'), ('Credit Limit Override', 'Credit Limit Override'), ('Transaction Reverse', 'Transaction Reverse'), ('Fraud Flag', 'Fraud Flag'), ('Fraud Clear', 'Fraud Clear'), ('Staff Create', 'Staff Create'), ('Staff Deactivate', 'Staff Deactivate'), ('Settings Change', 'Settings Change'), ('Token Redelivery', 'Token Redelivery'), ('Loan Approve', 'Loan Approve'), ('Loan Reject', 'Loan Reject')], db_index=True, max_length=30)),
                ('target_type', models.CharField(blank=True, choices=[('user', 'User'), ('meter', 'Meter'), ('transaction', 'Transaction'), ('loan', 'Loan'), ('staff', 'Staff'), ('system', 'System')], max_length=20, null=True)),
                ('target_id', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('target_repr', models.CharField(blank=True, max_length=200, null=True)),
                ('details', models.JSONField(default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('notes', models.TextField(blank=True, default='')),
                ('staff_member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['staff_member', 'timestamp'], name='portal_admi_staff_m_ce10cb_idx'), models.Index(fields=['action_type', 'timestamp'], name='portal_admi_action__c2c643_idx'), models.Index(fields=['target_type', 'target_id'], name='portal_admi_target__be2653_idx')],
            },
        ),
    ]
