# Generated by Django 5.2 on 2026-06-24 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal_admin', '0003_systemerrorevent'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='systemerrorevent',
            new_name='portal_admi_compone_bb8dbe_idx',
            old_name='portal_admi_compone_idx',
        ),
    ]
