# Generated by Django 6.0 on 2026-03-05 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_transactionlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionlog',
            name='transaction_type',
            field=models.CharField(choices=[('LOAN_APPLICATION', 'Loan Application'), ('LOAN_APPROVAL', 'Loan Approval'), ('LOAN_DISBURSEMENT', 'Loan Disbursement'), ('LOAN_REPAYMENT', 'Loan Repayment'), ('LOAN_COMPLETION', 'Loan Completion'), ('UNIT_PURCHASE', 'Unit Purchase'), ('UNIT_SHARE', 'Unit Share'), ('UNIT_TRANSFER', 'Unit Transfer')], max_length=50),
        ),
    ]
