# Generated by Django 5.2 on 2026-09-29 14:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0019_creditscorefactors_created_at'),
        ('meter', '0022_alter_meternotification_notification_type'),
        ('transactions', '0006_alter_transactionlog_transaction_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentIntent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(choices=[('PURCHASE', 'Electricity purchase'), ('LOAN_REPAYMENT', 'Loan repayment')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('currency', models.CharField(default='UGX', max_length=3)),
                ('provider', models.CharField(default='MTN_PRODUCTION', max_length=20)),
                ('provider_reference', models.UUIDField(unique=True)),
                ('provider_external_id', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SETTLED', 'Settled'), ('FAILED', 'Failed')], default='PENDING', max_length=10)),
                ('initiated_at', models.DateTimeField(auto_now_add=True)),
                ('settled_at', models.DateTimeField(blank=True, null=True)),
                ('provider_transaction_id', models.CharField(blank=True, max_length=100)),
                ('meter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='meter.meter')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_intents', to=settings.AUTH_USER_MODEL)),
                ('purchase', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_intent', to='transactions.transaction')),
                ('repayment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_intent', to='loan.loanrepayment')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('meter__isnull', False), ('purchase__isnull', False), ('purpose', 'PURCHASE'), ('repayment__isnull', True)), models.Q(('meter__isnull', True), ('purchase__isnull', True), ('purpose', 'LOAN_REPAYMENT'), ('repayment__isnull', False)), _connector='OR'), name='payment_intent_one_purpose')],
            },
        ),
    ]
