# Generated by Django 5.2 on 2026-09-30 09:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0020_loanapplication_intended_meter'),
        ('meter', '0023_energyallocation_meterdelivery_simulatedmeter_and_more'),
        ('transactions', '0007_paymentintent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='paymentintent',
            constraint=models.UniqueConstraint(condition=models.Q(('provider_transaction_id', ''), _negated=True), fields=('provider', 'provider_transaction_id'), name='payment_provider_transaction_unique'),
        ),
    ]
